### PR TITLE
User authorization and context

### PR DESCRIPTION
**Pull request by jnbooth**
### UserContext

Located in `src/contexts/user`.

#### Sample
```js
{
  id: '00000000-0000-0000-0000-000000000000',
  email: 'user@gmail.com',
  name: 'John Doe',
}
```

### src/components/Header.jsx

header

The header is now aware of login status. If the user is logged in, the "LOGIN / REGISTER" links are replaced by "MY PROFILE / LOGOUT". The former links to the user's `/profile` page. The latter logs them out.

### GET /login + GET /logout

Internal authentication managers to handle Cognito responses. Don't worry about these.

### GET auth.buskr.life/login?response_type=code&client_id=520e0dfqtk20438m739gmc223d&redirect_uri=https://buskr.life/login

login

signup

This is where the "LOGIN /REGISTER' button links to.

### https://auth.buskr.life/logout?client_id=520e0dfqtk20438m739gmc223d&logout_uri=https://https://buskr.life/logout

This is where the "LOGOUT" button links to. It's a simple redirect with no UI of its own.

### CODE REVIEW

**Comment by jnbooth** [comment]
The @southlane/cognito-jwt-verifier library apparently forces compilation to fail if your environment variables are missing, meaning I had to add fake ones into the .env file based on what would go into .env.local so that it would compile on computers other than mine. I didn't even know that was possible. Tbh, not cool.

**Comment by jnbooth** [comment]
Oh my god it's still happening

**Comment by jnbooth** [comment]
Thank god.

**Review by c4mino — APPROVED** [review]
@jnbooth woo!

**Pull request merged**
