### PR TITLE
Search component Style finished for mvp

### PR DESCRIPTION
**Pull request by mkr123**
Finished search component styling for mvp, change to react-datepicker instead of antd for date selecting.
Screen Shot 2021-12-11 at 2 42 46 PM

### CODE REVIEW

**Comment by roheunji** [comment]
[Create Search Component and Styling](https://trello.com/c/XK3xtAxX/55-create-search-component-and-styling)

**Comment by roheunji** [comment]
[Create Search Component and Styling](https://trello.com/c/XK3xtAxX/55-create-search-component-and-styling)

**Comment by roheunji** [comment]
[Create Search Component and Styling](https://trello.com/c/XK3xtAxX/55-create-search-component-and-styling)

**Review by c4mino — APPROVED** [review]
Looks great @mkr123 nice work!

**Pull request merged**
