### PR TITLE
Map component

### PR DESCRIPTION
**Pull request by apriljgranzow**
Screen Shot 2021-12-10 at 4 52 49 PM

I created a map component that displays full screen.  It loads a list of events from JSON and then creates markers for each one.  You can click on events to see an overlay that contains a photo, the event name and busker name.  Clicking anywhere else on the map will hide the overlay.

### CODE REVIEW

**Comment by apriljgranzow** [comment]
[Map View Component](https://trello.com/c/nPekqfUU/31-map-view-component)

**Review by c4mino — APPROVED** [review]
@apriljgranzow looks great!

**Comment by apriljgranzow** [comment]
[Create map markers from test data](https://trello.com/c/O89WfbIE/38-create-map-markers-from-test-data)

**Comment by apriljgranzow** [comment]
[MVP Info Box for Map Markers](https://trello.com/c/my5t5sN6/46-mvp-info-box-for-map-markers)

**Pull request merged**
